version: '3'

services:
  client:
    image: node:12.9
    container_name: client
    command: sh -c "yarn && yarn start"
    ports:
      - '3000:3000'
    working_dir: /root/client
    volumes:
      - ./client:/root/client:cached

  server:
    image: node:12.9
    container_name: server
    command: sh -c "yarn && yarn start"
    ports:
      - '3001:3000'
    working_dir: /root/server
    volumes:
      - ./server:/root/server:cached